name: Deploy FastAPI with Docker to EC2

# Pipeline này sẽ chạy mỗi khi bạn push code lên nhánh 'main'
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          # Script này sẽ chạy trực tiếp trên máy chủ EC2 của bạn
          script: |
            # 1. Đi vào thư mục dự án
            cd ~/house-price-project
            
            # 2. Lấy code mới nhất từ GitHub về
            git pull origin main
            
            # 3. Yêu cầu Docker build lại image và chạy ngầm (d)
            docker-compose up -d --build
            
            # 4. Dọn dẹp các image/container cũ không dùng đến để tránh đầy ổ cứng
            docker image prune -f
